ai:
  enableSentimentAnalysis: true
  lookback_period: 60
  model_update_interval: 1
  sentimentWeight: 40
  timeframe: 15m
api_keys:
  bybit_api_key: 0uoTqXMrfhwEPe2SMH
  bybit_api_secret: ePL14K15F1GWRv3Fc5EzKC8AoHKuzr8vyKiI
  cryptopanic_api_key: defb6fad0b3f58d8369f3cbcafea0c0e8727025f
bot:
  ai_confidence_threshold: 80
  auto_tpsl: true
  cooldown_period: 1
  default_leverage: 20
  enabled_pairs:
  - AAVEUSDT
  - ADAUSDT
  - ALGOUSDT
  - ALPHAUSDT
  - ANKRUSDT
  - APEUSDT
  - API3USDT
  - APTUSDT
  - ARBUSDT
  - ARKUSDT
  - ATOMUSDT
  - AUDIOUSDT
  - AVAXUSDT
  - AXSUSDT
  - BAKEUSDT
  - BALUSDT
  - BANDUSDT
  - BATUSDT
  - BCHUSDT
  - BNBUSDT
  - BNTUSDT
  - BTCUSDT
  - C98USDT
  - CAKEUSDT
  - CELOUSDT
  - CELRUSDT
  - CFXUSDT
  - CHRUSDT
  - CHZUSDT
  - CKBUSDT
  - COMPUSDT
  - COREUSDT
  - COTIUSDT
  - CROUSDT
  - CRVUSDT
  - CTKUSDT
  - CTSIUSDT
  - CVCUSDT
  - DASHUSDT
  - DENTUSDT
  - DEXEUSDT
  - DGBUSDT
  - DODOUSDT
  - DOGEUSDT
  - DOTUSDT
  - DUSKUSDT
  - DYDXUSDT
  - EDUUSDT
  - EGLDUSDT
  - ENJUSDT
  - ENSUSDT
  - ETCUSDT
  - ETHUSDT
  - FILUSDT
  - FLOWUSDT
  - FLUXUSDT
  - FTMUSDT
  - GALAUSDT
  - GASUSDT
  - GLMUSDT
  - GMTUSDT
  - GMXUSDT
  - GRTUSDT
  - GTCUSDT
  - HBARUSDT
  - HFTUSDT
  - HIFIUSDT
  - HIVEUSDT
  - HNTUSDT
  - HOOKUSDT
  - HOTUSDT
  - ICPUSDT
  - ICXUSDT
  - IDUSDT
  - ILVUSDT
  - IMXUSDT
  - INJUSDT
  - IOSTUSDT
  - IOTAUSDT
  - IOTXUSDT
  - JASMYUSDT
  - JOEUSDT
  - JSTUSDT
  - JUPUSDT
  - KASUSDT
  - KAVAUSDT
  - KNCUSDT
  - KSMUSDT
  - LDOUSDT
  - LINKUSDT
  - LPTUSDT
  - LRCUSDT
  - LSKUSDT
  - LTCUSDT
  - LUNA2USDT
  - MAGICUSDT
  - MANAUSDT
  - MASKUSDT
  - MAVIAUSDT
  - MBOXUSDT
  - METISUSDT
  - MINAUSDT
  - MKRUSDT
  - MNTUSDT
  - NEARUSDT
  - NEOUSDT
  - NFPUSDT
  - NKNUSDT
  - NMRUSDT
  - NOTUSDT
  - NTRNUSDT
  - OGNUSDT
  - OMNIUSDT
  - ONEUSDT
  - ONGUSDT
  - ONTUSDT
  - OPUSDT
  - ORBSUSDT
  - ORDIUSDT
  - OSMOUSDT
  - PAXGUSDT
  - PENDLEUSDT
  - PEOPLEUSDT
  - PERPUSDT
  - PHAUSDT
  - PIXELUSDT
  - PNUTUSDT
  - POLUSDT
  - POLYXUSDT
  - PORTALUSDT
  - POWRUSDT
  - PRIMEUSDT
  - PUNDIXUSDT
  - PYTHUSDT
  - QNTUSDT
  - QTUMUSDT
  - RADUSDT
  - RAREUSDT
  - RDNTUSDT
  - RENDERUSDT
  - REQUSDT
  - REZUSDT
  - RIFUSDT
  - RLCUSDT
  - ROSEUSDT
  - RSS3USDT
  - RUNEUSDT
  - RVNUSDT
  - SANDUSDT
  - SCAUSDT
  - SCRTUSDT
  - SEIUSDT
  - SFPUSDT
  - SKLUSDT
  - SLPUSDT
  - SNTUSDT
  - SNXUSDT
  - SOLUSDT
  - SPELLUSDT
  - SSVUSDT
  - STGUSDT
  - STORJUSDT
  - STRKUSDT
  - STXUSDT
  - SUIUSDT
  - SUNUSDT
  - SUPERUSDT
  - SUSHIUSDT
  - SXPUSDT
  - THETAUSDT
  - TIAUSDT
  - TONUSDT
  - TRUUSDT
  - TURBOUSDT
  - UMAUSDT
  - UNIUSDT
  - USDCUSDT
  - VETUSDT
  - WAVESUSDT
  - WLDUSDT
  - WOOUSDT
  - XAIUSDT
  - XLMUSDT
  - XMRUSDT
  - XRPUSDT
  - XTZUSDT
  - YFIUSDT
  - YGGUSDT
  - ZECUSDT
  - ZENUSDT
  - ZILUSDT
  - ZRXUSDT
  leverage_type: cross
  max_concurrent_trades: 5
  max_daily_loss_percent: 10
  max_daily_trades: 500
  max_drawdown_percent: 15
  min_trade_amount: 5
  risk_per_trade_percent: 2
  stop_loss_percent: 2
  take_profit_percent: 3
  trailing_stop_percent: 1
dashboard:
  password: changeme123
  port: 8000
  username: admin
system:
  currency: EUR
  use_autostart: true
telegram:
  bot_token: ''
  chat_id: ''
  enabled: false
