ai:
  enableSentimentAnalysis: true
  lookback_period: 60
  model_update_interval: 1
  sentimentWeight: 40
  timeframe: 15m
api_keys:
  bybit_api_key: 0uoTqXMrfhwEPe2SMH
  bybit_api_secret: ePL14K15F1GWRv3Fc5EzKC8AoHKuzr8vyKiI
  cryptopanic_api_key: defb6fad0b3f58d8369f3cbcafea0c0e8727025f
bot:
  ai_confidence_threshold: 80
  auto_tpsl: true
  cooldown_period: 1
  default_leverage: 20
  enabled_pairs:
  - 1000000BABYDOGEUSDT
  - 1000000CHEEMSUSDT
  - 1000000MOGUSDT
  - 1000000PEIPEIUSDT
  - 10000COQUSDT
  - 10000ELONUSDT
  - 10000LADYSUSDT
  - 10000QUBICUSDT
  - 10000SATSUSDT
  - 10000WENUSDT
  - 10000WHYUSDT
  - 1000APUUSDT
  - 1000BONKPERP
  - 1000BONKUSDT
  - 1000BTTUSDT
  - 1000CATUSDT
  - 1000FLOKIUSDT
  - 1000LUNCUSDT
  - 1000NEIROCTOUSDT
  - 1000PEPEPERP
  - 1000PEPEUSDT
  - 1000RATSUSDT
  - 1000TOSHIUSDT
  - 1000TURBOUSDT
  - 1000XECUSDT
  - 1000XUSDT
  - 1INCHUSDT
  - A8USDT
  - AAVEPERP
  - AAVEUSDT
  - ACEUSDT
  - ACHUSDT
  - ACTUSDT
  - ACXUSDT
  - ADAUSDT
  - AERGOUSDT
  - AEROUSDT
  - AEVOPERP
  - AEVOUSDT
  - AGIUSDT
  - AGLDUSDT
  - AGTUSDT
  - AI16ZUSDT
  - AIOZUSDT
  - AIUSDT
  - AIXBTUSDT
  - AKTUSDT
  - ALCHUSDT
  - ALEOUSDT
  - ALGOUSDT
  - ALICEUSDT
  - ALPHAUSDT
  - ALTUSDT
  - ALUUSDT
  - ANIMEUSDT
  - ANKRUSDT
  - APEUSDT
  - API3USDT
  - APTUSDT
  - ARBPERP
  - ARBUSDT
  - ARCUSDT
  - ARKMUSDT
  - ARKUSDT
  - ARPAUSDT
  - ARUSDT
  - ASTRUSDT
  - ATAUSDT
  - ATHUSDT
  - ATOMUSDT
  - AUCTIONUSDT
  - AUDIOUSDT
  - AUSDT
  - AVAAIUSDT
  - AVAILUSDT
  - AVAUSDT
  - AVAXUSDT
  - AVLUSDT
  - AWEUSDT
  - AXLUSDT
  - AXSUSDT
  - B2USDT
  - B3USDT
  - BABYUSDT
  - BADGERUSDT
  - BAKEUSDT
  - BALUSDT
  - BANANAS31USDT
  - BANANAUSDT
  - BANDUSDT
  - BANKUSDT
  - BANUSDT
  - BATUSDT
  - BBUSDT
  - BCHPERP
  - BCHUSDT
  - BDXNUSDT
  - BEAMUSDT
  - BELUSDT
  - BERAUSDT
  - BICOUSDT
  - BIGTIMEUSDT
  - BIOUSDT
  - BLASTUSDT
  - BLURUSDT
  - BMTUSDT
  - BNBPERP
  - BNBUSDT
  - BNTUSDT
  - BOBAUSDT
  - BOMEUSDT
  - BRETTUSDT
  - BROCCOLIUSDT
  - BRUSDT
  - BSVUSDT
  - BSWUSDT
  - BTC-26DEC25
  - BTC-26SEP25
  - BTCPERP
  - BTCUSDT
  - BTCUSDT-11JUL25
  - BTCUSDT-18JUL25
  - BTCUSDT-25JUL25
  - BTCUSDT-26DEC25
  - BTCUSDT-26JUN26
  - BTCUSDT-26SEP25
  - BTCUSDT-27MAR26
  - BTCUSDT-29AUG25
  - BUSDT
  - C98USDT
  - CAKEUSDT
  - CARVUSDT
  - CATIUSDT
  - CELOUSDT
  - CELRUSDT
  - CETUSUSDT
  - CFXUSDT
  - CGPTUSDT
  - CHESSUSDT
  - CHILLGUYUSDT
  - CHRUSDT
  - CHZUSDT
  - CKBUSDT
  - CLANKERUSDT
  - CLOUDUSDT
  - COMPUSDT
  - COOKIEUSDT
  - COOKUSDT
  - COREUSDT
  - COSUSDT
  - COTIUSDT
  - COWUSDT
  - CPOOLUSDT
  - CROUSDT
  - CRVPERP
  - CRVUSDT
  - CTCUSDT
  - CTKUSDT
  - CTSIUSDT
  - CUDISUSDT
  - CVCUSDT
  - CVXUSDT
  - CYBERUSDT
  - DASHUSDT
  - DBRUSDT
  - DEEPUSDT
  - DEGENUSDT
  - DENTUSDT
  - DEXEUSDT
  - DGBUSDT
  - DMCUSDT
  - DODOUSDT
  - DOGEPERP
  - DOGEUSDT
  - DOGSUSDT
  - DOGUSDT
  - DOODUSDT
  - DOTPERP
  - DOTUSDT
  - DRIFTUSDT
  - DUCKUSDT
  - DUSKUSDT
  - DYDXUSDT
  - DYMUSDT
  - EDUUSDT
  - EGLDUSDT
  - EIGENUSDT
  - ELXUSDT
  - ENAPERP
  - ENAUSDT
  - ENJUSDT
  - ENSUSDT
  - EPICUSDT
  - EPTUSDT
  - ETCPERP
  - ETCUSDT
  - ETH-26DEC25
  - ETH-26SEP25
  - ETHBTCUSDT
  - ETHFIPERP
  - ETHFIUSDT
  - ETHPERP
  - ETHUSDT
  - ETHUSDT-11JUL25
  - ETHUSDT-18JUL25
  - ETHUSDT-25JUL25
  - ETHUSDT-26DEC25
  - ETHUSDT-26JUN26
  - ETHUSDT-26SEP25
  - ETHUSDT-27MAR26
  - ETHUSDT-29AUG25
  - ETHWUSDT
  - FARTCOINUSDT
  - FBUSDT
  - FHEUSDT
  - FIDAUSDT
  - FILUSDT
  - FIOUSDT
  - FLMUSDT
  - FLOCKUSDT
  - FLOWUSDT
  - FLRUSDT
  - FLUXUSDT
  - FORMUSDT
  - FORTHUSDT
  - FRAGUSDT
  - FUELUSDT
  - FUSDT
  - FWOGUSDT
  - FXSUSDT
  - GALAUSDT
  - GASUSDT
  - GIGAUSDT
  - GLMRUSDT
  - GLMUSDT
  - GMTUSDT
  - GMXUSDT
  - GNOUSDT
  - GOATUSDT
  - GODSUSDT
  - GORKUSDT
  - GPSUSDT
  - GRASSUSDT
  - GRIFFAINUSDT
  - GRTUSDT
  - GTCUSDT
  - GUNUSDT
  - GUSDT
  - HAEDALUSDT
  - HBARUSDT
  - HEIUSDT
  - HFTUSDT
  - HIFIUSDT
  - HIGHUSDT
  - HIPPOUSDT
  - HIVEUSDT
  - HMSTRUSDT
  - HNTUSDT
  - HOMEUSDT
  - HOOKUSDT
  - HOTUSDT
  - HPOS10IUSDT
  - HUMAUSDT
  - HUSDT
  - HYPEPERP
  - HYPERUSDT
  - HYPEUSDT
  - ICNTUSDT
  - ICPUSDT
  - ICXUSDT
  - IDEXUSDT
  - IDUSDT
  - ILVUSDT
  - IMXUSDT
  - INITUSDT
  - INJUSDT
  - IOSTUSDT
  - IOTAUSDT
  - IOTXUSDT
  - IOUSDT
  - IPUSDT
  - JASMYUSDT
  - JELLYJELLYUSDT
  - JOEUSDT
  - JSTUSDT
  - JTOUSDT
  - JUPUSDT
  - JUSDT
  - KAIAUSDT
  - KAITOUSDT
  - KASUSDT
  - KAVAUSDT
  - KDAUSDT
  - KERNELUSDT
  - KMNOUSDT
  - KNCUSDT
  - KOMAUSDT
  - KSMUSDT
  - L3USDT
  - LAUNCHCOINUSDT
  - LAUSDT
  - LDOUSDT
  - LINKPERP
  - LINKUSDT
  - LISTAUSDT
  - LOOKSUSDT
  - LPTUSDT
  - LQTYUSDT
  - LRCUSDT
  - LSKUSDT
  - LTCPERP
  - LTCUSDT
  - LUMIAUSDT
  - LUNA2USDT
  - MAGICUSDT
  - MAJORUSDT
  - MANAUSDT
  - MANTAUSDT
  - MASAUSDT
  - MASKUSDT
  - MAVIAUSDT
  - MAVUSDT
  - MBLUSDT
  - MBOXUSDT
  - MELANIAUSDT
  - MEMEUSDT
  - MERLUSDT
  - METISUSDT
  - MEUSDT
  - MEWUSDT
  - MILKUSDT
  - MINAUSDT
  - MKRUSDT
  - MLNUSDT
  - MNTPERP
  - MNTUSDT
  - MOBILEUSDT
  - MOCAUSDT
  - MOODENGUSDT
  - MORPHOUSDT
  - MOVEUSDT
  - MOVRUSDT
  - MTLUSDT
  - MUBARAKUSDT
  - MVLUSDT
  - MYRIAUSDT
  - MYROUSDT
  - NEARUSDT
  - NEIROETHUSDT
  - NEOUSDT
  - NEWTUSDT
  - NFPUSDT
  - NILUSDT
  - NKNUSDT
  - NMRUSDT
  - NOTPERP
  - NOTUSDT
  - NSUSDT
  - NTRNUSDT
  - NXPCUSDT
  - OBOLUSDT
  - OBTUSDT
  - OGNUSDT
  - OGUSDT
  - OLUSDT
  - OMNIUSDT
  - OMUSDT
  - ONDOPERP
  - ONDOUSDT
  - ONEUSDT
  - ONGUSDT
  - ONTUSDT
  - OPPERP
  - OPUSDT
  - ORBSUSDT
  - ORCAUSDT
  - ORDERUSDT
  - ORDIPERP
  - ORDIUSDT
  - OSMOUSDT
  - OXTUSDT
  - PARTIUSDT
  - PAXGUSDT
  - PEAQUSDT
  - PENDLEUSDT
  - PENGUUSDT
  - PEOPLEUSDT
  - PERPUSDT
  - PHAUSDT
  - PHBUSDT
  - PIPPINUSDT
  - PIXELUSDT
  - PLUMEUSDT
  - PNUTUSDT
  - POLPERP
  - POLUSDT
  - POLYXUSDT
  - PONKEUSDT
  - POPCATPERP
  - POPCATUSDT
  - PORTALUSDT
  - POWRUSDT
  - PRCLUSDT
  - PRIMEUSDT
  - PROMPTUSDT
  - PROMUSDT
  - PUFFERUSDT
  - PUMPBTCUSDT
  - PUNDIXUSDT
  - PYRUSDT
  - PYTHUSDT
  - QIUSDT
  - QNTUSDT
  - QTUMUSDT
  - QUICKUSDT
  - RADUSDT
  - RAREUSDT
  - RAYDIUMUSDT
  - RDNTUSDT
  - REDUSDT
  - RENDERUSDT
  - REQUSDT
  - RESOLVUSDT
  - REXUSDT
  - REZUSDT
  - RFCUSDT
  - RIFUSDT
  - RLCUSDT
  - ROAMUSDT
  - RONINUSDT
  - ROSEUSDT
  - RPLUSDT
  - RSRUSDT
  - RSS3USDT
  - RUNEUSDT
  - RVNUSDT
  - SAFEUSDT
  - SAGAUSDT
  - SAHARAUSDT
  - SANDUSDT
  - SAROSUSDT
  - SCAUSDT
  - SCRTUSDT
  - SCRUSDT
  - SCUSDT
  - SDUSDT
  - SEIUSDT
  - SENDUSDT
  - SERAPHUSDT
  - SFPUSDT
  - SHELLUSDT
  - SHIB1000PERP
  - SHIB1000USDT
  - SIGNUSDT
  - SIRENUSDT
  - SKATEUSDT
  - SKLUSDT
  - SKYAIUSDT
  - SLERFUSDT
  - SLFUSDT
  - SLPUSDT
  - SNTUSDT
  - SNXUSDT
  - SOLAYERUSDT
  - SOLOUSDT
  - SOLPERP
  - SOLUSDT
  - SOLUSDT-11JUL25
  - SOLUSDT-18JUL25
  - SOLUSDT-25JUL25
  - SOLUSDT-29AUG25
  - SOLVUSDT
  - SONICUSDT
  - SOONUSDT
  - SOPHUSDT
  - SOSOUSDT
  - SPECUSDT
  - SPELLUSDT
  - SPKUSDT
  - SPXUSDT
  - SQDUSDT
  - SSVUSDT
  - STEEMUSDT
  - STGUSDT
  - STORJUSDT
  - STOUSDT
  - STRKPERP
  - STRKUSDT
  - STXUSDT
  - SUIPERP
  - SUIUSDT
  - SUNDOGUSDT
  - SUNUSDT
  - SUPERUSDT
  - SUSDT
  - SUSHIUSDT
  - SWARMSUSDT
  - SWEATUSDT
  - SWELLUSDT
  - SXPUSDT
  leverage_type: cross
  max_concurrent_trades: 5
  max_daily_loss_percent: 10
  max_daily_trades: 500
  max_drawdown_percent: 15
  min_trade_amount: 5
  risk_per_trade_percent: 2
  stop_loss_percent: 2
  take_profit_percent: 3
  trailing_stop_percent: 1
dashboard:
  password: changeme123
  port: 8000
  username: admin
system:
  currency: EUR
  use_autostart: true
telegram:
  bot_token: ''
  chat_id: ''
  enabled: false
